services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: reservas_db
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped

volumes:
  sql_data: