services:

  backend:
    build: ./backend
    container_name: reservas_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_SERVER=db
      - DB_USER=sa
      - DB_PASSWORD=ServerAdmin2026
      - DB_NAME=reservas

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: reservas_db
    environment:
      - MSSQL_SA_PASSWORD=ServerAdmin2026
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"