services:
  - type: web
    name: reservas-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
      - key: SEED_EMAIL
        sync: false
      - key: SEED_PASSWORD
        sync: false

  - type: web
    name: reservas-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
