sonar.projectKey=valeriacaro23_Laboratorio
sonar.organization=valeriacaro23
sonar.projectName=Sistema de Reservas de Laboratorios
sonar.projectVersion=1.0
sonar.sources=backend/app,frontend/src
sonar.exclusions=**/tests/**,**/__pycache__/**,**/venv/**,**/node_modules/**,**/htmlcov/**
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
